replicaCount: 1

image:
  repository: kamaljeetydv/go-web-app-devops
  pullPolicy: IfNotPresent
  tag: "v1"

ingress:
  enables: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific